### ISSUE TITLE
При check-deps проверять, что в разных конфигурациях не меняются install пути

### ISSUE THREAD

**Issue by likvidator3301** [skbkontur/cement#100]
Представьте пример: есть модуль someservice. У него есть конфигурация full-build, в котором секции install есть
```
- Deploy/someservice.dll
- Deploy/someservice.client.dll
```
В настройках проектов я для конфигурации Release указываю OutPath=Deploy и всё работает хорошо.
Затем я выделяю клиентскую конфигурацию, для конфигурации Client у клиентского проекта указываю OutputPath=bin\Release, и в модуль ямле у меня получается условно так:
```
client:
  install:
    - someclient/bin/release/someservice.client.dll
full-build:
  install:
  - Deploy/someservice.dll
  - Deploy/someservice.client.dll
```
Я начинаю использовать клиентскую конфигурацию в других модулях, и тоже всё работает хорошо. Но до тех пор, пока кто-то в моей цепочке зависимостей не переключит someservice на конфигурацию full-build.
Можно ли цемент научиться ругаться на такое, хотя бы ворнингом при check-deps? Чтоб путь до dll не менялся сквозь цепочку конфигураций модуля
